Repository fullcalendar/fullcalendar, pull requests merged in 2018-03, with the labels that each got.

#4040 Expose missing OptionsInput type and fix some jquery hooks types
  src/exports.ts
  src/types/jquery-hooks.ts
Labels: Accepted, TypeScript

#4071 Fix auto height in ListView.
  src/list/ListView.ts
Labels: List View

#4082 Corrected the swedish week header.
  locale/sv.js
Labels: Mergeable, i18n

#4069 Add translation of "year" in dutch
  locale/nl.js
Labels: Mergeable, i18n

#4014 bower: bump moment to 2.20.1, which includes Chinese fixes
  bower.json
Labels: Accepted, Core, Mergeable
