Repository fullcalendar/fullcalendar, pull requests merged in 2019-04, with the labels that each got.

#4582 Update fa.js
  locales/fa.js
Labels: Confirmed, i18n

#4589 adding viewSkeletonRender function to OptionsInputBase interface
  src/core/types/input-types.ts
Labels: View Rendering

#4601 Fix link to Google Style Guide
  CONTRIBUTING.md
Labels: Confirmed, Docs
